endPoints = {
    "register": "/register",
    "checkKyc": "/check_kyc",
    "checkHandle": "/check_handle",
    "requestKyc": "/request_kyc",
    "issueSila": "/issue_sila",
    "redeemSila": "/redeem_sila",
    "transferSila": "/transfer_sila",
    "addIdentity": "/add_identity",
    "getAccounts": "/get_accounts",
    "getAccountBalance": "/get_account_balance",
    "getTransactions": "/get_transactions",
    "linkAccount": "/link_account",
    "registerWallet": "/register_wallet",
    "getWallets": "/get_wallets",
    "getWallet": "/get_wallet",
    "updateWallet": "/update_wallet",
    "deleteWallet": "/delete_wallet",
    "getSilaBalance": "/get_sila_balance",
    "schemaUrl": "https://api.silamoney.com/0.2/getmessage?emptymessage=%sTestMessage",
    "apiUrl": "https://%s.silamoney.com/0.2",
    "getBusinessTypes": "/get_business_types",
    "getBusinessRoles": "/get_business_roles",
    "getNaicsCategories": "/get_naics_categories",
    "linkBusinessMember": "/link_business_member",
    "unlinkBusinessMember": "/unlink_business_member",
    "getEntities": "/get_entities?",
    "getEntity": "/get_entity",
    "certifyBeneficialOwner": "/certify_beneficial_owner",
    "certifyBusiness": "/certify_business",
    "cancelTransaction": "/cancel_transaction",
    "addRegistrationData": "/add/",
    "updateRegistrationData": "/update/",
    "deleteRegistrationData": "/delete/",
    "documents": "/documents",
    "list_documents": "/list_documents?",
    "get_document": "/get_document",
    "list_supported_documents": "/document_types?",
    "delete_account": "/delete_account",
    "reverseTransaction": "/reverse_transaction",
    "openVirtualAccount": "/open_virtual_account",
    "getVirtualAccount": "/get_virtual_account",
    "getVirtualAccounts": "/get_virtual_accounts",
    "updateVirtualAccount": "/update_virtual_account",
    "getPaymentMethods": "/get_payment_methods",
    "closeVirtualAccount": "/close_virtual_account",
    "testVirtualAaccountAchTransaction": "/create_test_virtual_account_ach_transaction",
    "getStatementsData": "/get_statements_data",
    "getWalletStatementData": "/get_wallet_statement_data",
    "statements":"/statements",
    "createCkoTestingToken":"/create_cko_testing_token",
    "refundDebitCard":"/refund_debit_card",
}
